version: '3'

services:
  app:
    build:
      context: .
      args:
        - DOCKER_ARG=sub_docker_compose

x-uffizzi:
  ingress:
    service: app
    port: 80

  continuous_preview:
    delete_preview_after: 10h
